# Generated by Django 5.1.2 on 2024-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='titulo legal'),
            preserve_default=False,
        ),
    ]
