# Generated by Django 5.1.2 on 2024-10-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
